name: "Check lint, types, license and application"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci        
       
      - name: Verify selectFirmwareWithoutProgrammingOption is false
        run: |
          if grep -q "selectFirmwareWithoutProgrammingOption = true" src/app/devOptions.ts; then
            echo "ERROR: selectFirmwareWithoutProgrammingOption must be set to false"
            exit 1
          else
            echo "✓ selectFirmwareWithoutProgrammingOption is correctly set to false"
          fi
        
      - name: Check
        run: npm run check
